tests: Add a few more cases for --sdtid and --v3 tokens
Signed-off-by: Kevin Cernekee <cernekee@gmail.com>

diff --git a/tests/export b/tests/export
--- a/tests/export
+++ b/tests/export
@@ -1,6 +1,8 @@
 #!/bin/sh
 
+TESTDIR="${TESTDIR:-.}"
 TMPFILE=out.tmp
+TMPFILE2=out2.tmp
 TOKEN="--token=279396402074015764735041244773131252103253001721722151344173126350250236671677634"
 STOKEN="${STOKEN:-../stoken}"
 if ! test -z "${VALGRIND}";then
@@ -46,8 +48,43 @@ if test $? != 0;then
 	exit 1
 fi
 
+$VALGRIND $STOKEN export $TOKEN --sdtid \
+	--template $TESTDIR/fixed-secret.xml \
+	--new-devid 'a01c4380-fc01-4df0-b113-7fb98ec74694' \
+	--new-password 'Correct_horse!battery&staple' >$TMPFILE
+if test $? != 0;then
+	echo "cmd 4 failed"
+	exit 1
+fi
 
-rm -f $TMPFILE
+cmp $TMPFILE $TESTDIR/devid-passwd.sdtid
+if test $? != 0;then
+	echo "test 4 failed"
+	cat $TMPFILE
+	exit 1
+fi
+
+$VALGRIND $STOKEN export --v3 --file $TESTDIR/pinmode-2.sdtid >$TMPFILE
+if test $? != 0;then
+	echo "cmd 5(a) failed"
+	exit 1
+fi
+
+$VALGRIND $STOKEN export --file $TMPFILE --sdtid \
+	--template $TESTDIR/fixed-secret.xml >$TMPFILE2
+if test $? != 0;then
+	echo "cmd 5(b) failed"
+	exit 1
+fi
+
+cmp $TMPFILE2 $TESTDIR/pinmode-2.sdtid
+if test $? != 0;then
+	echo "test 5 failed"
+	cat $TMPFILE2
+	exit 1
+fi
+
+rm -f $TMPFILE $TMPFILE2
 
 exit 0
 
diff --git a/tests/tokencode b/tests/tokencode
--- a/tests/tokencode
+++ b/tests/tokencode
@@ -1,5 +1,6 @@
 #!/bin/sh
 
+TESTDIR="${TESTDIR:-.}"
 TMPFILE=out.tmp
 TMPFILE2=out2.tmp
 STOKEN="${STOKEN:-../stoken}"
@@ -13,6 +14,25 @@ $VALGRIND $STOKEN tokencode --token 'http://127.0.0.1/securid/ctf?ctfData=279396
 grep "09816090$" $TMPFILE >/dev/null 2>&1
 if test $? != 0;then
 	echo "cmd 0 failed"
+	exit 1
+fi
+
+$VALGRIND $STOKEN tokencode --file $TESTDIR/devid-passwd.sdtid \
+	--use-time 1410710132 --pin 1234 \
+	--password 'Correct_horse!battery&staple' >$TMPFILE
+grep "67567106$" $TMPFILE >/dev/null 2>&1
+if test $? != 0;then
+	echo "cmd 1 failed"
+	exit 1
+fi
+
+$VALGRIND $STOKEN tokencode --token 'http://127.0.0.1/securid/ctf?ctfData=AwEByZLN5XVbh5OtVsfRb04CveKhPm6yki4MrshAIQb64DWw%2BDLXUhVT2NLyvMIljNdAqUCa7zyTpXeRdcT703jKW2Wqw6C2PfBsAoTgoXeTnCewG1P9U0WUnsclkurZlzj%2BjfEqmyjPXkBfYpVBTg9NzfG6g9WdDZren8LQ2GMSfhb%2FrFbMbV65YIkX%2BEJKTnQXSL7wqAY1zP1CD79VRlPpS%2F1bzOwBJmSuOhoNwdJTB%2BD%2BapTsYJSTVR2k0Hs8icCgHj0%2B%2FPnl3O%2FgLi8XXqyehAbhouF9UQYI2UlRCSZYVlz0yeVWu8NkhvOjEm66D8zVu48gFy6NaHJ%2BjR1xFveQCFJJRuA3vAU8rty6ES%2FIeHE7tvYcEEVY2klEjjqd4SAJ' \
+	--use-time 1410710132 --pin 1234 \
+	--password 'Correct_horse!battery&staple' \
+	--devid 'a01c4380-fc01-4df0-b113-7fb98ec74694' >$TMPFILE
+grep "72210624$" $TMPFILE >/dev/null 2>&1
+if test $? != 0;then
+	echo "cmd 2 failed"
 	exit 1
 fi
 
